"""Urls for Table Tennis Rankings."""

from django.conf.urls import url

from rankings.views import (
    CreateGameView,
    EditGroupView,
    EditTournamentView,
    FinishGameView,
    GameView,
    GroupView,
    GroupsView,
    IndexView,
    JoinGroupView,
    JoinTournamentView,
    PlayerView,
    StartTournamentView,
    TournamentGameView,
    TournamentView,
    TournamentsView,
)   

urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(), 
        name='index',
    ),
    url(
        r'finish_game/(?P<pk>\d+)/$',
        FinishGameView.as_view(),
        name='finish_game',
    ),
    url(
        r'^groups/$',
        GroupsView.as_view(),
        name='groups',
    ),
    url(
        r'^groups/(?P<pk>\d+)/$',
        GroupView.as_view(),
        name='group',
    ),
    url(
        r'^groups/(?P<pk>\d+)/join/$',
        JoinGroupView.as_view(),
        name='join_group',
    ),
    url(
        r'groups/(?P<group_pk>\d+)/game/(?P<game_pk>\d+)/$',
        GameView.as_view(),
        name='game',
    ),
    url(
        r'groups/(?P<pk>\d+)/create_game/$',
        CreateGameView.as_view(),
        name='create_game',
    ),
    url(
        r'^groups/edit_group/(?P<pk>\d+)/$',
        EditGroupView.as_view(),
        name='edit_group',
    ),
    url(
        r'^players/(?P<pk>\d+)/$',
        PlayerView.as_view(),
        name='player_profile',
    ),
    url(
        r'^tournaments/$',
        TournamentsView.as_view(),
        name='tournaments',
    ),
    url(
        r'^tournaments/(?P<pk>\d+)/$',
        TournamentView.as_view(),
        name='tournament',
    ),
    url(
        r'^tournaments/(?P<pk>\d+)/join/$',
        JoinTournamentView.as_view(),
        name='join_tournament',
    ),
    url(
        r'^tournaments/(?P<pk>\d+)/start/$',
        StartTournamentView.as_view(),
        name='start_tournament',
    ),
    url(
        r'^tournaments/edit_tournament/(?P<pk>\d+)/$',
        EditTournamentView.as_view(),
        name='edit_tournament',
    ),
    url(
        r'tournaments/(?P<tournament_pk>\d+)/game/(?P<game_pk>\d+)/$',
        TournamentGameView.as_view(),
        name='tournament_game',
    ),
]
