# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_game_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Enter the tournament name', max_length=255)),
                ('has_round_robin', models.BooleanField(verbose_name='Are there Round Robin rounds?')),
                ('no_round_robin_rounds', models.PositiveIntegerField(default=0, verbose_name='Number of Round Robin rounds')),
                ('round_robin_finished', models.BooleanField(default=False)),
                ('has_elimination', models.BooleanField(verbose_name='Are there Elimination rounds?')),
                ('no_players_for_elimination_rounds', models.PositiveIntegerField(default=0, verbose_name='Number of players for Elimination rounds')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='elimination_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='rankings.Game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='rankings.Player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='tournament_admins', to='rankings.Player'),
        ),
    ]
